Lesson 2
ESBOL2312/Kolesa-Upgrade-FE-2021 pull request #2
Opened 2021-09-25 11:42 UTC by ESBOL2312

2021-09-26 03:56 UTC, airtwister commented
В целом, все хорошо. Есть только пара замечаний, напишу в коде

2021-09-26 03:57 UTC, airtwister commented on index.html
> +<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
preconnect-ы тут лишние

2021-09-26 04:01 UTC, airtwister requested changes

2021-09-26 04:01 UTC, airtwister commented on index.html
> +    <link rel="stylesheet" href="https://unpkg.com/modern-css-reset/dist/reset.min.css" />
лучше утащить это к себе, и подключать из своих папок

2021-09-26 04:01 UTC, airtwister commented on src/css/style.css
> +    --blue-lighter: rgb(214 236 251);
Этот синий чуть не такой как в фигме. И почему ты всё перевел в rgb?)

2021-09-26 04:02 UTC, airtwister commented
и еще если уменьшить размер окна меньше 1040px, то модалка ломается

2021-09-27 05:07 UTC, airtwister requested changes

2021-09-27 05:07 UTC, airtwister commented on src/fonts/Open_Sans/LICENSE.txt
> +
Я имел в виду только reset.css залить к себе) Сорри не очень понятно выразился похоже. 
Лучше вернуть их как было) и убрать лишние оттуда

2021-09-27 05:14 UTC, airtwister requested changes

2021-09-27 05:14 UTC, airtwister commented on src/css/style.css
> +    --blue-lighter: rgba(214, 236, 251, 1);
Ты точно в фигме смотришь?

https://www.figma.com/file/i35UhuWwNPoVp70rwiYttW/Kolesa-Shop?node-id=1%3A10966

![image](https://user-images.githubusercontent.com/5547378/134848613-18815e76-3bf3-4ed0-8282-a77d2a630af4.png)

![image](https://user-images.githubusercontent.com/5547378/134848646-bc4d18c4-9b86-45dc-b265-2df3aaa54e44.png)

2021-09-27 08:47 UTC, ESBOL2312 commented on src/css/style.css
> +    --blue-lighter: rgba(214, 236, 251, 1);
удалены шрифты. 
![image](https://user-images.githubusercontent.com/24974525/134875325-173ee895-94f4-45b9-a2ec-df266884988d.png)
 я думал это один и тот же цвет )))

2021-09-27 09:56 UTC, airtwister approved these changes

2021-09-27 12:27 UTC, merged